services:
  - type: web
    name: drims-backend
    env: java
    region: oregon
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
    plan: free
