services:
  - type: web
    name: drims-backend
    env: java
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATA_MONGODB_URI
        value: your_mongodb_connection_string
      - key: JWT_SECRET
        value: your_secure_jwt_secret
      - key: CORS_ALLOWED_ORIGINS
        value: https://frontend-4ag5vq86j-harshith1476s-projects.vercel.app,http://localhost:5173
    plan: free
